name: 'ci'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
jobs:
  ci:
    name: 'CI'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: 'actions/setup-node@v3'
        with:
          node-version: 16.x
          cache: pnpm

      - name: install @moonrepo/cli
        run: 'npm install -g @moonrepo/cli'

      - name: moon ci
        run: 'moon ci'

      - name: moonrepo/run-report-action 
        uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
